version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: ./backend   # Dockerfile provided below
    depends_on: [redis]
    ports: ["8000:8000"]
    environment:
      - REDIS_HOST=redis

  ui:
    build: ./frontend  # Dockerfile provided below
    depends_on: [api]
    ports: ["5173:5173"]
