version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]

  api:
    build: ./backend
    depends_on: [ redis ]
    environment:
      - REDIS_HOST=redis
    ports: [ "8000:8000" ]

  ui:
    build: ./frontend
    depends_on: [ api ]
    ports: [ "5173:5173" ]
